package com.davekerr.projecteular;

/**
 * @author Dave_Kerr
 *Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
 *1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 *By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 *SOLVED
 */

public class evenFibonacciNumbers {
	
	public static void main(String[] args) {
		
		long start = System.nanoTime();
		
		int sum = 0;
		for(int i = 0; i < 34; i++)
			if(findFibonacci(i) % 2 == 0)
				sum += findFibonacci(i);
		
		System.out.println(sum);
		
		System.out.println((System.nanoTime() - start) / 1000000 + " ms");
		return;
		
	}
	
	public static int findFibonacci(int num){
	
			if(num == 0) return 0;
			if(num <= 2) return 1;
			
			return findFibonacci(num - 1) + findFibonacci(num - 2);
	}
}
